Import('*')

SimObject('MemoryModule.py')
Source('memory_module.cc')

SimObject('MemorySubModule.py')
Source('memory_sub_module.cc')

SimObject('MemPoolCtrl.py')
Source('mem_pool_ctrl.cc')
DebugFlag('MemPoolCtrl')

SimObject('DisagMemInterface.py')
SimObject('DisagDRAMInterface.py')
SimObject('DisagNVMInterface.py')
Source('disag_mem_interface.cc')

Source('disag_drampower.cc')
DebugFlag('DisagDRAMPower')

SimObject('MemPoolManagerXBar.py')
Source('mem_pool_manager_xbar.cc')
DebugFlag('MemPoolManagerXBar')
